#!/usr/bin/env bash
# ARC - UserBot
# Copyright (C) 2021-2022 TeamARC
#
# This file is a part of < https://github.com/RACHIT-KUSHWAHA/ARC_USERBOT/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/RACHIT-KUSHWAHA/ARC_USERBOT//blob/main/LICENSE/>.


echo "
            ARC ON FIRE 🔥

      Visit @ARC_USERBOT for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyUltroid ; fi
